[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "b89e8258e522cc9e5692a4bdbb420c779eab4080"
libgfortran_version = "5.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "7bee3a9ceb199fe25bcd9ed427d296e602b401971263c30344c16a52b74b6ace"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "983eb0832dcdbf926581ff638d9c94314549fd51"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "b85efd43550bacd33d0a5ab6c9d6ae790360db70b4def700a566824308150fc5"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "d78337c052d0ab4a8f0c88d01de6be794d6b4221"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "cb278ecf6312dd42deab5df08ce51db22e4d317f18eeb181e4dbc48ec177c4d5"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "71f0d5ed59f5c86f8dc97f1c333d01515d3f4d5a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "7d7a266a2f0f6d8bfd976e87ce97aa9f1b6efe67183dcbd5b9cce4f54dd6bdeb"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "117adc018c7148e03a90d42df3d91b4f387a5a34"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "d8df9a7e20ed18a7819626ec0436839cf6ca58cfa91ded5707884212f0ee61cd"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.aarch64-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "3c75784dfa4d12d71815ce4b29d4c5e852104331"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "ad541cb27aa0a1a861d7cbe29d581c7fca5ae65714880821d38abeb4d3aabe1c"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.aarch64-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "c7b4bf3874c02d4900092378954d3252f6f916b7"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "cf219add2a58cd275c9893c97cbc1f351898329cfe89cc160218defc5bf3d995"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.aarch64-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "47f45cee525c61cd9d2f3810a31ebb139ad267f4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "db6a847b02d5913ee0128af567411cbe4adb012542124661b61565b9139b5e1f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7c0012c6eb6775e77eed110665e81210d17a1362"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "1e8a656a6c5c0eabfb3a54e613e23ec1a7827ee967d8dfa682ff3e114901f481"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9ca84db8f3e154ef4131b28b9beaa47abd864fd3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "608f63cb8e7765de36b5b03f677eaab30118235c4ae526c95332513d0e36ca46"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c63f57e4d529cb2fa6f44294b588acd6f1005086"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "2f52daa0786e97a25235d7c87508438b5e2f97642d78edff5b0eee31752dea19"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a37a0159430241eab0a65477e21d6de1411e60b9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "bc359c11c216261a0543502896c8863ec90471f2501d80584a0133c4091c6a2e"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7be8745a8ca3f215f423545fc988ad41195b855d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "5347986ab458954b6d9ce373006829d61200296b6c69a7318f63ec1d93560280"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "441f87e80d7e96faadf2e3463ac54c5496d84fab"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "cfe1a2c13bd4d5025944c22b2be1a84122fed03820742de4c798b1bac5a37e92"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5d434e8b54de1df158494312a9019d6d4e6d38d1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "c5449f0cb5b80caf98fd21bf561fda3935f68cd9959abdc0b1ddb159e5355436"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "12524c818442a2c62cbc1e8ccf1b146e6a0b460e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "b31cdacf0694818c6a5d8530ae0d2a813c42a58bb0f2aa94e3a32c06203bc282"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8382645b3a80ac3eae09a2b6fab6a0ff602273e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "7f9f5c6ddd219c6554f1b84d4ab070904fddd58f5ff8fd35664a119c3b08a864"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2257bfa8a1184b67535dba104acc0919386cec86"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "c1e42762d8b5f4ee8f29af131a8e11cd9353eaabd818ad4a4206dc65f5cea6f7"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d35ccac6e4edb1d7612090973e7e4343a43259ed"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "7d411ecc73c0f1e5ceffa93c51b6eba30e5a84c8346d6e0c7c52d9fa27f9f7f9"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "b61def2780d1c5c7c991e07a02fe1256199a2c06"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "18dba995408ac786ecd192e6aaa685ade28b2b20284218acc820fc1689a752ac"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.i686-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "9a76b2fc22560730388a4c148df05f2ac53cf589"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "1e475aa1bff1413c215fc7a51ae2326d32b724abfa222b4eaaa2820ac83ed133"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.i686-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "50b3bdbe9f863f36b30b3369fcf8f2b433833ad7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "674859f5a8887b1618aad3129ee00a5f48ca8d63f31aae32546e2699d96be5e9"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.i686-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "aa6b757aa276f3004e03ab25002d4c2728c3aea8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "52a089ef236626920de46c352bad0280a434970463ce40546c37b2b1240fb498"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.i686-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "79b370105abd2ee4357ec4294c643fcdba1e43b7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "904b315ed81f6681b05c174da7ccd13a39d1db3f9ade8e7ac66184bd6a424d36"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.i686-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "05a2d0aa80d4ac2721cb71978274e45512ac7af8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "091255b326fd83608fdf431d0993e2d9be2bdad292c93d6369accd2c9d1fb656"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.i686-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "0b229a600df7600186a50c822efa259ef88d8568"
libgfortran_version = "3.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "65b2c5e610a7f2af15b4899a5a63aa8b125f99127e48ff4fd23691c70a745074"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.i686-w64-mingw32-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "af7b2436ec735b05abbd5f257049cde1400fea70"
libgfortran_version = "4.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "9075a38cdbe444994253f27241cdcb9a56ef987cac2bb88923977555f452eb83"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.i686-w64-mingw32-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "980d6a6fe8306baddc744aed3c9d3d9a6cae18ea"
libgfortran_version = "5.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "c7eb670cf1b319700bfe4d546cdcfbc0c7976306ab4aec79315955132ac769f9"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.i686-w64-mingw32-libgfortran5.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "4850baa8eee62fe2a7405a92264dac91f81b2951"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "e38d5d69c2d6220b8f1eaecd83111783ec8b03403eb32b4b35c907d03098de5e"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "c5f95325dbdba6705bdcecfe02a8087ea2f6862f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "fc137f1507e215d734314ee70d6ef88cb3f109dcd1781721b5db940917693b3d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "fa0196bb7f96db8b7c169c1519dc06f84abf7e64"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "94ea1017767a918047ec89210e09eac81457ebd3022ffd1ad7c9e2597b09f20f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "6372be27bb2545947dbc9a3d55eded7dc87f3371"
libgfortran_version = "3.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "a17594856feb12d6179908845399c7c5e61be20e258c91edc3bf1a00151f1a90"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "4f0aaacac01419676f0d94fa230ed0bd915f14b1"
libgfortran_version = "4.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "340a064af069941ad49b11419fec7efa73543125e877430cd003b46570d19d96"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "46242a39750d3b6fecde947ca0c4a00f748baaba"
libgfortran_version = "5.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "ad4669487472218bcef0ddf6c0668d34457272c3cd3c840197f618343ae79cdc"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "9790b0dfcba9f132a83d39317272760915f04931"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "01abf62dc2e35e33ab4d37d88299db13bcaf6219feb321ef6078bbdb41b35510"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "b6aacd30bd87ca739b7009d15386ea689fca6c2e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "cf0fbed71840ffb8518e63171efefd9e3f8e59e2d81fb1d62a0b7c5d693531c7"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "b657738285863bb9ab411209197ce6e9c85f0888"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "0844109b4cccc950b0544db29dfb60c67aba3e88f1a28e48e8e1bc54d6770a2d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "3467fc9381d18e22e72dc7dfbf28870326f3a12a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "8c95dd8462b42fc34d649054f44c0e862a866379abe5cb5e22b99611ee7371d7"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "32f93cf78b876d87fb12a39866ef1878feb3c28f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "9a1598db07117d07577a09689f86066ce54174e9541249b357ab9e340d34fdfb"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "fa6eb1fb4023d734baf98588f0f05bf245256be6"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "94d3580051a7d9d314cf5314a1def75a13f0b93ca1f169794a8336d60e244633"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "1d5fe495f6ef508a8a7b7f43e0fadd3c085572a7"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "d7dbb50386db37ef8ecde606d9bae1b0d513505074306c5ad3796a4dac5d0df3"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "897052299e29ae0367bffb85c0f80cfe17a8394e"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "8a56d3265072d24b0e3d08f06285a8223d254b90c671924f6b691538e6355876"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "5f37898b1410eec5eac2dd28ee47c02c096ff623"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "6360dae8e0726bae4066a2c4f95dd225ae8b312e4134a3848be07f4cc552aaa5"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "21ab250ea0a1866b44e8a055cc21c4bbd9486ab8"
libgfortran_version = "3.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "8867cdd64cf5a928300a9acae8926f24530546cb19ac57f61bd964100fb9a56e"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "30b9eafb1278dc008f6bcf575201764ec2fdc4fd"
libgfortran_version = "4.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "6026baeadbef8761819d992c14a0e55a503b4553f00ce4b9acbca37450d27c67"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "e8918981f93c3488546d215013516b2206df5064"
libgfortran_version = "5.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "7219c4acab65bbedc6af17146668a878252d0b8ff9ccdf0fb69b59b5c83eb60d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.11.15+0/SPRAL.v2023.11.15.x86_64-w64-mingw32-libgfortran5.tar.gz"
