[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "bf3e3303f9595c22da4729ffee43bb23aa5906f4"
libgfortran_version = "5.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "e6edb21cc6f3f7646bb9e0d9ff40df233cb34d7f64a9a8d117db759976e70e79"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "68f6acad3b9abf618a93809e465b37f6403e74a0"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "6a4eb597639de192c5bfcc611f242e1df74b1d4ba6e97ffc62fe22512f22e752"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "673b34caf92f704ba2ae6f2c4e3ac8ce4e2519f9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "bcdd4042da39ae71e739457b8304c07b39355d1da8e6925496da413dea2e3d2c"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "a950ac69497085bd1462b56c075e6fa831cc279f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "1dbde56298696cc04b851a25b8bdb5887791798472218b128384d4b99f544463"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "72d538fb151dc056813edb962f55b8f6d87cde24"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "dcb46acaf2e41f14848e2458806493fd6684fe4dd8c7064b9c5092a3461b7367"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.aarch64-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "0ea0c133178ff41b2bdf19646fa48334dcd6ac2e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "b11efddfa00d4b142bd4a6f7c33e12b71fd44403bc890092a4d1a4c3884ede88"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.aarch64-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "881d442a88cba2e7a86299daece9ae64a74154fb"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "9db14d6f2802d64121f854e6ff8d087eebbe51ff916bbbca6e98fd21756339cb"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.aarch64-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f2370382a4e8e0f81c3b300a76c8d0682914c753"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "d2ee00a5248ab679e777a7fe7397a1d0f5f285b43017f419f33665b694c61850"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5d2be360c103338b32a958639e47c6430ec4b15e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "8c4c42d6a7f5d701a56d2f07492dd2422862912d5e293235f3edd7d4bfdb9031"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1c3ab46f5abc20c67d10ef7cfb29333d4aa30b41"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "05cabc3585d1eb46475d46d54ad07798762c57d8d0d2d88a813805868f063f25"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "088c4ecdbbbaaea298716280f295993d14deff3a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "e4babded579e3e04a9750e17208d518ae98bf7588f36ff84b4c5ff58668bfa25"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3460d64e51b05dfcf5eed2123c55ec591ef65af1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "f7caeafba09a2aa9da508244e982ea6f42c41e8c01c8d3ac2ab6eea449fb8e7b"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2f9999025db3b36ac79c779530afc83d6c3e3228"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "f4b49e1c6bb9cc96c3950a9280c82ff794e795cbb4e492dbcd9a4bd5ca925190"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "834831bb4cb5a42e2d61325cf93b4d4b33dfdc08"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "246606d939ebde3dfe2014986b658db3f6a1c2ca7b707932b53a3e1f5d3caeb9"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "767b3fde8afd273e4c19c3a9e8f926fc052db3f2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "55b6783c6188ec69bc5d0cdb7f2b956f5e15e5c42fbda03ac6aa4c6ca67266a2"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f08cc1ff8669bfa8b10e1cfdeeb8f09ad787799e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "a1df7657845b08f3086f736862f098ecc0fc999906c2cb1d921b09fe75dadd17"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0e2b38795ee1ac4de3d4d369a8a1951ccb64b7b7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "3eb580f29f077a772fbe062ab91fcfdb36573670f7e75f190209eaf94798df9c"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5564b5a9a721a39303298bb75f23686d8de53512"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "c569bb5d7b70f80489fb022cba8b44d17cc567d45098d85359adf8435d043ab0"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "00615806869479b091ceabe08226ed6c5fde5e6c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "9accf6b13456b6110a6de0b3a0b1b8832ef1bcab2cf1f0b4e333ccdf00ab1df7"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "c51d4f11e5e70d9aa64ab311b191c64b683d7d3c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "ed185622408617929cc2c03e3d22ace92cb219c069787ed6dd42bd8695486eba"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.i686-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "b132dbbb7d3981fcc396d2ea4fc17259ac10fe9b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "5c526db897311fc22776f2c4fdd3d60e537fa4eddf29968e709d1d849389401f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.i686-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "ebc6378a5eddf7625a60579d6da25af19cf2a879"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "a3bc4edfc7d19612548f3e28a00a60e8e988f532f6038eda3866d0341cdc6ea0"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.i686-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "9bc68fb06e4012cb01c19b758dab4928aba1e5b0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "22bd0d7ddb659e06888d28a8105c90e630641be5f638b39b8f18bc4efef07765"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.i686-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "78abee6aeee1c999d15fa82934a4992c2b10ba49"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "a8103634a196e5c38e80af04ecc5a55f8849721866996c41098d300da4be338c"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.i686-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "cd0faca28efe05f13b65c805e972068683eb0957"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "1bcb4637eb4372eee8135d503587b3a49df4b0a9bcbd9a819053862093f2dc32"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.i686-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "771694a4ae503040c9cc6fd7c21ca55329261ea9"
libgfortran_version = "3.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "920d7f1d21cdc61b6bc09f84e79e691495bb61efeb878bcae44fd50af3c142aa"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.i686-w64-mingw32-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "a8bf54caf1a0e221eaad63095cbf5c204990a5cb"
libgfortran_version = "4.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "9166ae5c5b4903deb8d4ab2e3478931579d3989b7e0d3c5ac4660248dd1983b9"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.i686-w64-mingw32-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "a1d0dcd8cbf1e8ecc0434f20c12116458df3368a"
libgfortran_version = "5.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "fe047119e63cbd734f3538157a3480d83e47abdbd4aba68b74961646def31973"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.i686-w64-mingw32-libgfortran5.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "bbca4a6c8acce7a3d66ede961e3dedd7925320b5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "5653ecee5c5eed81b0892f562f9eab9b820af350af8ced20016e3970c2e70e9b"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "2299b2efe379d02eecc03a1749a3a94e7c5460c6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "8b11a6c30c07ce5e87db83a9f6373fe3417432b7d9d36e3783c98e8535fe18da"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "fe6d8ae255367c09573bc87b4d47078e7497434c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "5b41c72a47205b3e3f3dd8947ca0dbe9f52fa85d6727750b01bc7bb5562e7ceb"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "471da7059bf12b034fc9cba402941eee1c05d032"
libgfortran_version = "3.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "941d5276a9dd2b018781ee32f5a88f88893889a658c6d709bf74c74006bd7163"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "a5efb3cd8255bb53275936304a78cbc094895e73"
libgfortran_version = "4.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "f02f63c30b2ceb0630abc0f689b6f56407b743853bcb38e87e6ddaaa597858d8"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "02228731edec726745d6be3491da5149ac5a051f"
libgfortran_version = "5.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "d20f631e5c0052d3da7479b90a834205c5441f5d3c9e5d094d627ab9c616e8c5"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "edf46cb9ac1cbfc5045d957f822631e01d4a6183"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "2a2af758269be4122dfacaae9fb619c192fc896838cad8e80aa0e4711e145b21"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "efb845e319e0a6080ce8e8efaa9156a602b77973"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "a877df135753fd46303e63a1ae0b7fda12cef5b2ded50ae77259a911c0f31ddd"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "3474ed4e1c89803dca08e7982ee2f1046c01cc83"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "f46a29d4033341ffb2b9156becbd1b2f7d5e78d280bcbe03218afa37a08c5740"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "662bf68592ee2791ab0b7c5efff10ed16a8d8cf1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "aa16a641c07fc3a1781f3bc3b26201fe7ebc408acc8fedb0642cf625b1fe9e6f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "ed94789b6891bf9f46c5bf4c12f33ec95f0dadc7"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "1c99787a6cd801cfc86d5a1b679c8515ff5a70414724464fbad959ccf9439224"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "9abc020b25bb72c6aa4c032adba896fd25637b05"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "d98127161f1609281a66687455e75945445486f3f79759169352bc63bb230550"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "454ea9c0f71c344497f2bead1154fc5d63b634c7"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "29e6ffcaf36f88f3b2d87ecc52a9612e1d2293d6f2a85241b86196f40781a68b"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "21d45ee5e4b0a84a609b1d89ce6031c60c625d74"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "ac68855798f3a21c488498b121994c45d4b95be87cc683084e5acbb3e2eb9d7e"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "f8c14d7fe441f4c28e5715e4ab03d72e315595cf"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "ab3ba841c6da40bf18aba0e505d1184b15c1025902d5274386b31e08e4dfbf1c"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "e0e5699e8c90613dea783d24eb751bf900227035"
libgfortran_version = "3.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "e53a251306d874d9b77c5c29010ed43f0230edbea26bb2cb4cdbc878af65f7c3"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "4c0b2fb0bcaee3829436867f2730f2679bb0798e"
libgfortran_version = "4.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "3f6d02552f68e1a88a16353f879b7ebc9d11bf108c0ec567dc0abf70c7299034"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "56b846e372dddee33d2309e89e2b2b16aaf07c83"
libgfortran_version = "5.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "048c2d93b9f80db41ec75905449a0b87ec97ccb1e7e791720fae2f3d423ef01d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2024.5.8+0/SPRAL.v2024.5.8.x86_64-w64-mingw32-libgfortran5.tar.gz"
