[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "87331a2cdcac90dcc09fcc6468f3f8a5cb8815ec"
libgfortran_version = "5.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "417c90273e14a5befc09727a183ebbf582445863f92f07bf35daeb7b68d82251"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "229b50f618961c4ddda9c7f84572685cbcd795e8"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "c5e86ded295363df8aac5c05708dc960bb62b64e8cc635b5ec1a944b2e9887ab"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "eaa59dcaa48e728621d904852e2b806c194b1b2e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "06a890905f1640bf5475bf180bd2fca6a22f74c3b0ef5882e81f31f418bc7584"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "f747c263b46abed0b30a31df36eec3cee9958e6c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "28917d688f71ac2d9a210a9c64f7cbe59d4733b26311c7179578c141365322bb"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "d898cfbf9698ed3a58af24a4780ce6b3c6ebfdd5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "5863ffb7042a72bc55e4404e0c383ae65ddde6f1dbb7bfbedc01b79bd3bb6dd1"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.aarch64-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "3fb5b14bf76f604afd7ec326905fffed612cbdca"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "68ddb18e69550aba67d20c749892c8d195862ccd04b473347d7a9f9f4e217c5d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.aarch64-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "df7a1961c5762fb92ad6cda01066594d82da4d86"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "54b56cbc913f81e3dffc1feeb656fa104e1d74d94e268f22d3e4a240b3d77399"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.aarch64-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9fdcb7b9c37aa52bc8bb721092fcd52d6b7f2252"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "c8bea6b3c76110cd35d94a9fa10543a52b2c146c95b16d44157bdbf5dfe81231"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6ba07d7dc6c3688fe7b95cbb9e0a8aa04a7646d"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "1549eec50fb84c37b5add89465a33c66a966ad5b3450ec9b9ff5282d4a49525d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "499d96626a99822a6161588cfe65dee03f915c8f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "e049411a77f229428a7296041fcb03b5ac2ea09b516a7d27f38c013192966cad"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "781334848b390282e1e33a03403398a0b59c8f69"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "986b1aa2d58da329f6bf6b34756545f588860fa83016aae0db57d7bec45812be"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "230692aad9289ba617d13c25846e056a4717a9c5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "8cbb621480e47ef9289a044f1005c3b5c4ed50308d229e539e1326acb617fb60"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6bbe390bc7c61817b7ef645cb6d3ce09593848ef"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "5ff6fc6486947b9406015c420eabf41f00fbb70b72520e281c5599d6f15a8a91"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d0289bd285cb765466920433f7224f57494e0212"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "d4d36424395d5b4a25f2af7284f215b5c2b10619d8a3ab8efbdcfc41b3a2de49"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bb53cbb578fcf19778b60ba5220fdd64a22002c4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "0e685fc4dfd782b634f5d1eb60a5f8fb078fad3dbdf44a04a58d2764cc76c64f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "00b1d9e6ea67ef4a5637ac083514ec2cc4899c28"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "655d2d705299d7f4edd18df7da4839d86630d6d930c5e5f7f93a7693bab64a52"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "743bb192c5373eab127a1ad3f13b8eba78a2454c"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "1580a9e6de37f4dc30086dda1c54bf88dbb99c8718627866686d08ac8e933b0c"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1ef01ff7125522ce52be73f59110f5ea4f64369f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "f8158196683ba0c80ae6c5344696b74ca806eb7c32bf399154287d154deef10a"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dcfccbe618c8b6e119d4e052125934c03dc5bd26"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "932b946f70ee806d4a2c1dba151ee31b9489159ebb9cedd32b5bed584f413573"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "c29a22a4665a84817f472b0072d94018f2a3bf31"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "a324bdbe22c7467655ba2c2add0f98f05d7f10b29e9dfe1dccf3b5cc33dee80f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.i686-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "d9fec4313366505517e67ed256910112809eccc3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "d81d064a4a7ee2a3b54ac33a88e6f13ead7f864fceaf6f4d98b4d8424463d776"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.i686-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "af51c3b68225595faf62b58569f2d7def25043fe"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "5ee96ac67fe0a1c2fd78d23681193f628561a438c5efaf9207891f3e03046655"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.i686-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "5df9f52bcc61a04e2dc6ef1c7d3ca28debe901e5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "adc344194c0a73d02fdfc15c2e4f7764e6e636d10b7a9937d973003dd7b726ec"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.i686-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "3e755f98503a11c12dcaf48c8d0ea9ec35fca255"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "30a6d41471238eb58841ec624ba687b2b6cde4b701637357e841f6534cebf60d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.i686-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "4c587bd5b66cb06b4524c1ebd6c7d9411fb8ebf8"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "17f4eb1ccf7a4a063050a1ee79e4430d1fb848740205e2a26771047918a5c8a3"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.i686-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "d4029ff0c5b799b82ff2d3f411fe11e9d6bf4782"
libgfortran_version = "3.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "4a1309c2b7b7f792cf88c178e5d2d18ad37e08718c96307c71f4ef62e0c263b8"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.i686-w64-mingw32-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "5c4db91f13e569a9fea5bd1f0a8e4b2ed026b7bd"
libgfortran_version = "4.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "6bb2b3151813d18d6667fc120866e9dd2b03c6764c5462e57156ae5674c67229"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.i686-w64-mingw32-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "52c29a5507d8faa7d936497b2fb5ed0517303d65"
libgfortran_version = "5.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "74bbbd17204886cd1d8143c096ca160942367e9f4ab5054d74bdf9a47f3ddd62"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.i686-w64-mingw32-libgfortran5.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "c26e417853e653abd2e564ab9400fe51ae86d05f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "de435148efaf03aef2bde1ec539130b16281eb6bc02691739ad0142903163b36"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "f6f0a7ff7bce2a651c44ff4c24d56bbea69e7c22"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "8feb05c34d98a5d6725df9b2aa858c7808e8c5b98c9d6bff0afcf41f858397a2"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "616439f59032857cf2652d6e449129aa06904be0"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "1fdb96d7bfb3f1d40fbe19f0b252923f2bcde5f0b8718702c5cc25d86cc009ba"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "718170e0d6f47a97c96fb2ae0938b27ae9c84ba7"
libgfortran_version = "3.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "939639d3b14d61f94eaacac4ff6294a61ff6043bbeac339b16028e7f288c1917"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "00c5e3f7843c6def72f76bf5273cc76088d470eb"
libgfortran_version = "4.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "9b01cff31aad895dc640482e954669175d8bcec19f3824ee076acd515d12990f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "0c9761a4c62bbe1f880cabd62621d2904dba379e"
libgfortran_version = "5.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "2656212434472db0177d18e770c00980c8627ea459789518f1bf6f25b13b5a12"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "7298f00c4c3d8ddf93c82363305a5b6a8fdb7628"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "9457c2ce61d514313233c981894c01a1005ed6e1dc0c544a3a4332ec16c71757"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "bfc8f10e2bf14443a9183365a8bdc8277e04c936"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "0a3220e47e0e126e23f5148f519855fbdfed4e7a377bffc67553c27cfc7b294f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "c892fa46fcbd3fc23676be986854859755b12eb6"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "886aa8fe3d84bb40e1221f21c13128a793e63e4c0bc8c93c54490fee229deb6d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "fb91308def6a97300b1018743e0c03a86b85a8b8"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "4c676bcba24bb126442bbee4ebe178950bf8c807012ff8e7d10ed94c241e72d5"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "6f1ce7c7a9ae15fc0483c6d4ea426b42a5e24fa2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "1082852676e1e5dc2eeaaeb378125e76674cbca2f6d09be3d046e2db05a0fc90"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "86e5633bc46dd432bcf6943baebd23547cbe161f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "e5ad7f401d8a1a85d2b60e3455d2bca45a44366533a523b63208c2fba57ac2d2"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "36651fb55e86a6cd818d7c5f40d877cb6887344d"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "56df4617278cdce7552857d6b1ea8316388d33a532b09760dccf3e1189cb4cc9"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "21f7ba1e0b579d3e67f35321137b545a1eaa9312"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "4fc7900ae775562f6c3c79a7f6e677761214b905e0815caeef30cfcfac87c42c"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "f4f1fc3e5acb871f1acb4277d8c606fae7b1bc55"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "2d0b7200d927a07e857c8423dfbe348c58ad8a9c2b28d1a1dfbba8ccd4935c80"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "7b02fde7b772319b1f027a579a715b7bde88a9c4"
libgfortran_version = "3.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "d4637d0b2d5b82dbf7ae472e0d2c7af78e2f430da078c4b0fc4d5bfdefffa7f7"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "ef70458f139509395cf70fe2af85502e7019c83b"
libgfortran_version = "4.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "5467815645d869c1ff507318a37990fcab94582fd66d58e6b04785003f21e148"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "86a4e4cd980b5a2ad5ca60b535168a004ef27c48"
libgfortran_version = "5.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "1468673782a317cbbbe36d96c07cf4b30f27a460d1db9ee75af0a6a4fc379794"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.9.7+0/SPRAL.v2023.9.7.x86_64-w64-mingw32-libgfortran5.tar.gz"
