[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "7803edaefd512ecf07368c973fa1705d6bc60cd0"
libgfortran_version = "5.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "113f1b79def0101a471ff76184947fa85e4e2808932dff18da47094a345eb95c"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "68f0be1eceb9c858a55ece1a719e5efb1ccfb19a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "e91d4fd816abce01a70fb31037ffd4799ab204bbba96a06f03fc1da437c69bb2"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "fdd86ee9cc362ebbbccf4ad9a95c8960f1f9365a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "24e860a9d732b06de4e59dc8cfc380246ca74be7783351219bc85aa2ade414cb"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "299a26b254ff673bda4f0e517379c094075586b7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "355d94bf7124f373a58b71406d04a6caded44817b5232e029d9c53102ea1e157"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "a446da73adbf62a82744889b8ab45f7109a6ac78"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "b05cec5ef42381e51836a2a06d1df1a081e8839bfc70bde3655b6fd940699b89"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "a779b3c1ccb93f6fd09f2e9813ad5f186676e9a0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "aafe2d5bb2d4bc4900c2314d40e93415d38ebce970d783a543207044c9e9b8cf"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "9cc2794b9633be95ba59a46e5bb09224f3ab7a81"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "679ec5965949c315d71100495149102fae14690332937964a1d28b3766d63b87"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "663a06f175cf98ede055dff6e5b1f97e21cf9ad6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "01f793a68af5f4c77ad443b99445003562593f5340ae1f0040544e2442167c12"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "11865fbe38223644163b28d79710fe43794ee2f4"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "6e8b8cca2540523fd36ced580583283f549382db38f81e58294c94931fda065e"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f73c466999c97f117d93e2329039acfd5d762135"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "f65c5e118df421c1f6189acffad96362ba6f8baaf803dbd23a6c84d476209215"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "71108d48a103389ae268c35caf6667b177ce13ee"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "7246647c385ddee3871091f6822393ec0b7eef40b2d4b2c09991ead9b2edf427"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8a663572d34f6274c4bd1f739a385e0cac76dd0f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "19af9935ed5be813a1e301bc5afa8b440650a1b167b3cee13a72eb969cd34213"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d682620c03258552b464ee01bafe032c403f79a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "d0a7d664816e8f85406d39d689bc498f87db371f53f035b08096e8ee31d3e9df"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a7d08618963d69a938059903ccca4d4339566123"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "d4d8d97fb40cc149b7c08feb9d7065df6b324fe52e44763bfc295f8aa9eb6bdf"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6667064ad06da6e3b64f122d4514faa1320fcf14"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "71c6715a137f63fa2bf423903ed6f488c9da4cb748761d973946d9db5127a95b"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e89be2da83d56c9725b3f232f1e137e842b710f2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "95666ca40aa0880ff8b7961f95d2c534cc13491f968944f5035a414c3fd8f0c5"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0cd62daf04c8e2aebc8740a21b3a58bf02bc74b4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "8839963ab39d080573aa7fb6d049feb7d5ce429ceb7ca3ffe759916a1f4ad17d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df9c288fb49452ae6b2a8388f16f2393c7610493"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "03ccbe8096faa53fda03869567e4cdcc5903e73f94361d6a578f3c72559610bb"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "552bf70d6cc51a88083867dbc25dd91986b6b6f9"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "530ba4fe3b1e322e6a7a93bf5da37f02f8619c0b17b9ba70132a46e43412fbe3"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "4ebe90ae902d62937ef138ea7558b007e227ae02"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "9b62eb5429e3070f3f283830d5926ab89c882c2abb80ccc7ef8fbac7e15e0f6d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.i686-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "a84f2983c64f03c5c0979d99df97bf3ee93e7526"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "59ab1fde2dc1c4aa776d6a747307b2b2e6781a673b054abf2469d2256fca9244"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.i686-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "6a796f67772e34162dd2cfd14eed6f25e270f94b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "776b635c0b07053f59889be6354b7ed1cd23253c76012b69ed319ebf9ab5e611"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.i686-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "a30a151540934e4c37845b4401549bcef28360c5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "12704178172625db04087b357acb37f57f8af4af9fe2979bb602389428d40648"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.i686-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "ebf876c80376931355e77a2cd63a8cbc60bb709b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "6f6a27bf01736b40969e55ba32f0ff153a07b138fa5f23d2b4e215fe338c3c51"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.i686-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "7b99f4b93eb705d1a87216f7f34aeec0406fd35f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "0d6672770c06b19d2e57cd47e3e54a2c4d1455c5e4a72f7e9e5121e5556e8fa8"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.i686-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "04d5d412ab16b96281f382dc76662d00d6621b1d"
libgfortran_version = "3.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "0ee4ff6439c1458767f5d886d407e028acabae744cf03fb4a357ae1fca32967d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.i686-w64-mingw32-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "25689fc6288c87d08d88efb1371da9a4ed2b1462"
libgfortran_version = "4.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "392512b66d0fced349cd16b9d2c89fb290212d918ab2a8492791be3f3845bc96"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.i686-w64-mingw32-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "c3a444ad48cc944e41b0c3a5adbcc13d66604189"
libgfortran_version = "5.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "d404c8dab7a73215228425ce9d7988ca6d53ac2cd29c4f7c42d02a5189496831"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.i686-w64-mingw32-libgfortran5.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "1731b195befa0d4dd40e8bf60468085b022a80e9"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "a121072ae4e40741b0fe8848d84455e62168c028d76fed962d03848f9ddbfc45"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "fd3d729b2ba92d1776f4e1b722dc120c0aed0442"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "9f3992986b404fd995a231112404bf736dfe296301b96c01909f76802825d408"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "fd178b7ccca06aebc2da078b64014093de7dfd2e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "ea3934b9f711234b85d3677ea4ed7183e1356a90627026d99bdcb8d513082306"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "7599db8a19bcc994db311053029a59b3dfbb7fbe"
libgfortran_version = "3.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "8dccf8e20ca642c1248186ff63224d88c9397822e4f0d542f7ca2f462a8ef83d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "d45b6b8c1d6fd23d348dd04b3860979df2bb3730"
libgfortran_version = "4.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "747bb6f0464fa076f4176047d36d12a72002fee3fd004a649e4b1935b8d96c1d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "e0c031c32c186a3b4b8bbc9d853fc1699eb60d75"
libgfortran_version = "5.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "bb5c6657d6b65de55b1ee1698a8d83580dd4e7de7acc354860c341f6a8b52b0d"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "8ba50b38a9c4b985cee0a78906da93b12e5f7537"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "6207af805ebf35321fae1245d73b3032cb1295fb46b1f326d9914723e2a33484"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "4afea2b5fe7694daa95b3eed9a6758ca8b071807"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "1c0bd310deed423184c2e28a9042c660a9591acaf4d42f497cf112ae38c6aae8"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "460b62756db586d3cbf14a87af471ed3d1272f30"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "b219501a9091bc4c9471d0f9165adb8bdace9f384dae913cf2d634f7a0d41afc"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "00ec2cd75daf32e818b7afab4ca75bb80f346630"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "be91da5ea087b92e2537c69cbce0fb2f862e9bdcd6e638420d07827a6b451963"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "020a7b3410a1181a79953bdbf54e4db8e93a2c3b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "e16fc2dbeb5bba88e7d06ac6f568337b10cd553f8e0212c1e97599b1a7cec401"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "2124b68c5e7963939418c6abef31736625a1d90b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "2d43a4ce6374a696e91138961dcd346b93a323a62df9474811c88f1fcf6c0abf"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "d2f2cc4d3c13d2e86681a29dbb3f00c9e8fe4149"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "171610d30b743310e380fb3bf33af3f6bc3eaab25128bf37734edab9323ca8f1"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "2e69f9fb7853823ab4ce94f6103d01d2469b839b"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "a019e25d8c6b719372a25da7a8b6e24929742fd2ba745cda15141cb79f50b242"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "50d0315282015d57cd9e21cc4eb879bb5782b9d3"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "9c5271aad69d5c30ab7b644c077c8d8c39a767731ebb34d35fe36ebe071565b4"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "f6414ff76b5a10e459bea6321b01e00b856903c7"
libgfortran_version = "3.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "cca29903285b634e6be2c70a86467d906a580601828c00872a055fdb9f30dfe4"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "c59ed1d9cb176368b65124d26c9b423d97397f45"
libgfortran_version = "4.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "aa29d35cfd5b13d38d0fe56c5d2a79f0fd6dd52b27fca2eb15ca0966387a9a2f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "11325b71adbae9edda7da0d3d49e7035cb7b51d7"
libgfortran_version = "5.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "b46fed704d8df3524e292654410dd39218234692898e29b219c0e7e36e118921"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.8.2+0/SPRAL.v2023.8.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
