[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "d7d9c1f0828d44c9c1bd8c3d35858abf57f11fca"
libgfortran_version = "5.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "3138a4f64c9e86d46985e0866c649ea35396a4bebc7e1cb1d08d23d4037f57b0"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.aarch64-apple-darwin-libgfortran5.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "bfbc55558265b4522c965e4945404b6730e609ca"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "c57c7e08528be33f22ae36ede0751bbc667f0af7465bbeedb93e4c3b95a2fcc4"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.aarch64-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "7c4174b10fd790d431a4fcae2f456f63fa78aa06"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "79c30c0008555743bfa4dac3b5eab6f4e14d24522e22e573e5405788331b7a79"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.aarch64-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "41a729635486c95feb6a66fe3cab6af6896cc3ca"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "b7f1d204e88b4115e9bb83e72a1e36da365b0be2c135880016f565491ce88b1a"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.aarch64-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "c1f709961b7605cdfc35e2aed8cf725a5de5b7c7"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "5c213663bf7655f4831f34e3c58aeb775a24c89ac19053c9e31bb079d2f6e6bb"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.aarch64-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "59781d70f26d4192133368ae07ba89974848283c"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "5639d0c41cef24145517df15288349d9cd736d5025204632580e252ce0efa0a5"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.aarch64-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "aarch64"
git-tree-sha1 = "691e4d690fb0a9f4f57db32a61a99cfd915dcc06"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "63a80487bb183ec979737b20a54faf0c641db5a8c36feea47eac63649050a0c7"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.aarch64-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d31dc1a5874551d0c89619253396b07b31f9a179"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "fd63f0a0572a99561d30314706f8d8119aa2e4f9350a3c2863c01ee451f7b760"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d725d3626bcc7a51c3499bab0dc56724beccfda1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "7651201ab352fd9f0bac32acf2b3102e0663782e551858886547e0774832512f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6027f93da9b4dec0cdddaf661527ce4969f2e62b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "32010a799718485ae186a493af36cf673511e64ca19eb2abdca8122ab475d154"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e629d76a0f46801c9000484d35e0a8f9749a3a53"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "5c497e78ec345adf4c4e72ecb0ffac8541b5c730198c770b0e653e96a345a787"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d246f707bc76bc28909300293c8bcbd5c8a07705"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "e89eb894b4df2a9aec4e43fd3b3fe37fb82725d582fb5341596ada167cbf1bc0"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3884e851588ad7451f6f3f2aecc51f7b519d99b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "9c763aa75d1f702eea79fd88e212f327336726f58a5455bc2d643640cfc87ab6"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "00a7050f436df72b9aab073e145cd0af63ab8845"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "27e9cfe5810e17e668f9fa26f5e8a3095d301169504f509b318b368747d1221e"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "75e0c4fe514dac74bab4758b1e433c389b3f5d98"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "863c0d3d671521711e45286f0af0f804f8195f70ad044112f4375dc36a9d0731"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3931fd86bef06dcb357b4df274e8f4e63f2a4aae"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "f792865bc376496570d86de231d6e984c513810fb5894a0d0e451feaf82281ec"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3f708bd7f45e836e89301239db1c72e7c0cd27d2"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "8ec8ede37671ea1d4ef94f861816459a18763d4ef5e8b9f8e8d10129b2ef6d2a"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5aa66cc562c4aeb567fcd116ebe688853721493d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "55ad734731797c50e29e54a977d9ad2937469b237fccc15ea648d642c5b4a23e"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[SPRAL]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d35d977ce2eba80e847802c49d84a82f1654f339"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "431272e48d612b7804c3244f666f498c0c4ad0b6c86d0622d4bb1ef02c7e8c76"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "c89347d9dc7a51bb58dd77c447e940dadc48dde5"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "a0198cf0ed64f551e5e7bd18f8de3bafcb6d9bf72c62b814bacd95cc9737419b"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.i686-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "afb1555dad9dbccafb38e76a1a18b509f98a49bd"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "ac36b84f08b1af5d2d3bb3f33222c003d05491dd30cbb6942c45d9b40f15a7c7"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.i686-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "1ac1beb23e930dcecc6068e52aefb7dfaf0cc205"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "b8bf21cdfbc021e6682b5ec5af803d53f3306ced11cd6b213e5a38222c0bec36"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.i686-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "c0bd4dddf1d012d421e7ce5b0ca586a5f3fa9e9a"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "97a4af6f735cb76478bfc39cff7990d41382c0ffec000079b8408e00bfcf4bd0"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.i686-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "89b5966faf17edf816588a5b638ca86abcaff483"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "056a78616dcc4921302584e256e38d78d7edf79a4695671d5551cef51ea7b323"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.i686-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "3d159ac81bcddfc6a1eb509fbe19b721b33dcaea"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "a28d227e43dfed31cf517b40da7bde58ddd95500d9004abbd3ca14ad4193bac3"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.i686-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "516d19bfee0a7a2ef4b6475b46a9d5ec3688b466"
libgfortran_version = "3.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "817bda975a499d8b5bd21c8f89bca5aab10b478e3f45c308638475a908b1b9e3"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.i686-w64-mingw32-libgfortran3.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "a287e9961c161d478a1fc93854d8e29d5c1279f7"
libgfortran_version = "4.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "8841ca0619dc343510f01550e788a9b360efd2a0a9e497a8d6573ae93a8abee3"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.i686-w64-mingw32-libgfortran4.tar.gz"
[[SPRAL]]
arch = "i686"
git-tree-sha1 = "14f9f7da61d23def555afcba35d2b02e6f2a7f49"
libgfortran_version = "5.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "84409b95d59a833745af4b443f20e81e5bfac0757cad5a51b325c6e6a8077a01"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.i686-w64-mingw32-libgfortran5.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "261140cc727c5eecab17d79bfb2f87af7299907c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "fee0c0c0ab1435f07d4c27932d8c87c302c3facc6725537f19fd928d23159c1f"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "01479b4f20f069a39acdef1887f3be683d0764b3"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "65d53ee7dde220b8b5f389578656935552361754efe75c602031661393eb8363"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "powerpc64le"
git-tree-sha1 = "2ba1f2b4e4d3723aa31ca81057f438e97f5bd65a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "86fad7cc9788abeeb127204471180a20431586f0a719e569a056f552ce614055"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "d2b08fbf76f4733afb1a40760dc2d9b6cdc6c63d"
libgfortran_version = "3.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "1322b43b0f0b382ca2d9ae67fc16055519f9ea307fb84a2295f9f9de0985fdf3"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-apple-darwin-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "bcfd5806176b8654d59ccf86b5ebe09f9d3a9ee6"
libgfortran_version = "4.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "30f2f6522160c96a75d34b6901db116d0bff9df17a44495c26fac01ddfb440d0"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-apple-darwin-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "8a925a9986588db8c2f78ee36308487fd0236db0"
libgfortran_version = "5.0.0"
os = "macos"

    [[SPRAL.download]]
    sha256 = "3ef6a2e5de01ff31bd2a0cdf4018e0c273d5bd6566a763380cd0f064a39c4210"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-apple-darwin-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "203ddd6e83b91375c6030790e6585a6a3c1a85e4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "71ba08b4c57cce248fab8b1d6eac2f1d79eaccb0ca3f696fbe74d70ab9c09511"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-linux-gnu-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "b2851d255da677e7c448607e312c64f2d94297fc"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "009008ef2b26b53e3a7c1cacf8259fd9a5bce64a9f902713f5317aba750b3951"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-linux-gnu-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "1d83757338f29e5766f417ed742ac6e1e7c084cf"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "16294a06b173d8b8ccc6dbd44646b4037bca740a6cf0c35a96e7c1e54cbeeaf4"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-linux-gnu-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "120c06a72dfab74dfc4d411a420e1646d14cbb89"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "cb73c70a46d84754f24fae33a9ce9d88bcb5fb6da886154c0a508feb2a876f92"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-linux-musl-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "bdde00fdd7214baff0f4d5c60144218774e37082"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "3847507966979d74bb1188d8c71179e0df1823be96cdaf15d9c5cb63f831623b"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-linux-musl-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "e0d2397cd2f6ce2a88ebe37e511fd46a38d84442"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[SPRAL.download]]
    sha256 = "04645c6a85d37004c0a3df5d911b2f72098d110c02e3f8706426bcaded06c7d3"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-linux-musl-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "310b4393782e66227590e46b9a76e5c3126c1314"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "6e6b65f50f1b4b067409c77fbfa1cef0313a4ebfc5dbcb59a88f143bee3f8557"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "0769445c569f519462bd804f71c75f67e6452cf3"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "2a7b7559c88e73be3220041dae281de319dc4d888b6e8fdfd63767c46f9d1f30"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "2f1ddadf7828bb4d39a683eb925574d8920bed58"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[SPRAL.download]]
    sha256 = "6edd0581c5a6468a5edd9ea5d0018e8221549454a18903b639faf720d7c17bc4"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "918550ff8bd8c51ee42ad76eefbbb94c0ee9296a"
libgfortran_version = "3.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "a67e4b2b7b2effbb7835b9af3ce046ab6cbc9f85f3c999671bba2cccef9eedfc"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "16b7c3dbe17786b26c521ca680a313feded13fa1"
libgfortran_version = "4.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "e850d988a29b55f2081e0194156e07655f07938ed16ae578b37499588b000270"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[SPRAL]]
arch = "x86_64"
git-tree-sha1 = "769790883d56c3bdd1a46c01544e55d7c9543031"
libgfortran_version = "5.0.0"
os = "windows"

    [[SPRAL.download]]
    sha256 = "01fca2e438e31fb790a0e71896733483b8f4091091e8c48b4a6ece9a3ed28ef3"
    url = "https://github.com/JuliaBinaryWrappers/SPRAL_jll.jl/releases/download/SPRAL-v2023.7.4+0/SPRAL.v2023.7.4.x86_64-w64-mingw32-libgfortran5.tar.gz"
